language: scala
scala:
  - 2.11.11
  - 2.12.2

jdk:
  - oraclejdk7
  - oraclejdk8

branches:
  only:
    - master

matrix:
    fast_finish: true
    exclude:
      - scala: 2.12.2
        jdk: oraclejdk7
